### ISSUE TITLE
Transfer of clang compiler from Xcode 5 into Xcode 7

### ISSUE THREAD

**Issue by DanErikPetersen-Serato** [devernay/xcodelegacy#28]
Would it be possible to add support for e.g. embedding the clang compiler toolchain from e.g. Xcode 5.1.1 and have it as an option within e.g. Xcode 7.x? Alternatively, is there a good resource out there to dig into in order to be able to do this and potentially submit a PR to this repo with an eventual implemented solution?

**Comment by devernay** [comment]
You can take a look on how it's done for the gcc and llvm-gcc compilers. Just take care to add a version number to the clang binaries so they don't conflict with the current clang.

It may be difficult, because of hardcoded paths and conflicts with the current clang. I never tried. I will let you do this.

Personally, I don't see the point in using an obsolete clang, since AFAIK all clang versions are backward-compatible, and I would rather use clang releases from macports or homebrew.

It is rather easy to have another compiler (macports, homebrew, or whatever) as an option in Xcode, see http://stackoverflow.com/questions/19061966/how-to-use-a-recent-gcc-with-xcode-5

What you should do for a PR is the same as with all github projects:

- fork it
- clone the fork on your local computer, modify, commit, and push to your forked repo
- click the "pull request" button on github.com


--
Frédéric Devernay, Research Scientist, INRIA
frederic.devernay@inria.fr

**Comment by DanErikPetersen-Serato** [comment]
Thanks Frédéric 👍

I will give it a go when time allows :)
