### ISSUE TITLE
buildpackages privileges

### ISSUE THREAD

**Issue by DrLou** [devernay/xcodelegacy#8]
Really love your script, and thank you for the work! I think you may want a privs check on the buildpackages step as well. Extraction of man pages, etc. is expecting to create dirs...

**Comment by devernay** [comment]
Just tested in. Indeed, man pages don't get created, problably because of permissions, not privileges, but they are not installed anyway.

The error happens on the first line (although I told cpio to be quiet), but only usr/libexec/gcc/darwin/ppc usr/libexec/gcc/darwin/ppc64 and usr/bin/ld are kept from the unpacked distribution.
```
	(cd /tmp/XC3;gzip -dc Payload  |cpio -i --quiet)
	((cd /tmp/XC3; tar cf - usr/libexec/gcc/darwin/ppc usr/libexec/gcc/darwin/ppc64) |gzip -c > XcodePPCas.tar.gz) && echo "created XcodePPCas.tar.gz in directory "`pwd`
	((cd /tmp/XC3; tar cf - usr/bin/ld) |gzip -c > Xcode3ld.tar.gz) && echo "created Xcode3ld.tar.gz in directory "`pwd`

```
I'm closing this for now. Please comment if you thinkit should be reopened.

**Comment by EricFromCanada** [comment]
Changing the command to `cpio -id --quiet usr/bin usr/libexec` will extract only the required directories, skipping the share/ directory and the resulting permissions errors.
